"""empty message

Revision ID: 86abb1d750d2
Revises: 221e4207e9d8
Create Date: 2026-10-07 19:44:07.663748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86abb1d750d2'
down_revision = '221e4207e9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chat_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_chat_user_id'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('content')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chat_user_id'), 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_chat_user_id'), ['user_id'])

    # ### end Alembic commands ###
